# Simplified pre-commit hooks for WSL2/Windows compatibility
repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
              node_modules/|
              api/node_modules/|
              \.git/
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              node_modules/|
              api/node_modules/|
              \.git/
          )
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        args: [--severity=warning]
        exclude: |
          (?x)^(
              node_modules/|
              api/node_modules/
          )

  # Python formatting
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: |
          (?x)^(
              node_modules/|
              api/node_modules/
          )

# Global excludes for WSL2 compatibility
exclude: |
  (?x)^(
      node_modules/|
      api/node_modules/|
      \.git/|
      dashboard/node_modules/|
      logs/|
      npm_proxy_snapshot/|
      repos/|
      audit-history/|
      gitops_deploy_.*\.tar\.gz$
  )
