#!/bin/bash
set -euo pipefail
# ------------------------------------------------------------------
# Deploy Container Monitoring Scripts to Critical Containers
# Version: 1.0 - Integrated with Homelab GitOps Auditor
# Maintainer: festion GitOps
# ------------------------------------------------------------------

# Load configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config-loader.sh"
load_config

### CRITICAL CONTAINERS TO MONITOR ###
declare -A CRITICAL_CONTAINERS=(
    [100]="influxdb:database:high"
    [105]="nginxproxymanager:networking:high"
    [111]="OmadaController:networking:high"
    [112]="wikijs:documentation:medium"
    [122]="zigbee2mqtt:iot:high"
    [128]="developmentenvironment:development:medium"
    [130]="wikijs-integration:integration:medium"
    [200]="github-runner:cicd:medium"
    [1250]="adguard:networking:high"
    [1300]="wikijs-integration:integration:medium"
    [1400]="netbox-agent:monitoring:medium"
    [2000]="github-runner:cicd:medium"
)

### FUNCTIONS ###

deploy_monitoring_to_container() {
    local container_id="$1"
    local container_info="$2"
    
    IFS=':' read -r name type priority <<< "$container_info"
    
    echo "📦 Deploying monitoring to CT $container_id ($name)..."
    echo "   Type: $type | Priority: $priority"
    
    # Create monitoring script for the container
    local monitoring_script="/tmp/ct${container_id}_monitor.sh"
    
    cat > "$monitoring_script" << EOF
#!/bin/bash
# Container Health Monitor for CT $container_id ($name)
# Generated by GitOps Auditor - $(date)

CONTAINER_ID="$container_id"
CONTAINER_NAME="$name"
CONTAINER_TYPE="$type"
PRIORITY="$priority"

# Memory thresholds based on container type
case "\$CONTAINER_TYPE" in
    "database"|"automation"|"iot")
        MEMORY_WARNING_THRESHOLD=70
        MEMORY_CRITICAL_THRESHOLD=85
        ;;
    "cicd"|"dashboard")
        MEMORY_WARNING_THRESHOLD=80
        MEMORY_CRITICAL_THRESHOLD=90
        ;;
    *)
        MEMORY_WARNING_THRESHOLD=85
        MEMORY_CRITICAL_THRESHOLD=95
        ;;
esac

# Check memory usage
check_memory_usage() {
    local mem_used=\$(cat /proc/meminfo | grep MemAvailable | awk '{print \$2}')
    local mem_total=\$(cat /proc/meminfo | grep MemTotal | awk '{print \$2}')
    
    if [ "\$mem_total" -gt 0 ]; then
        local mem_used_actual=\$((mem_total - mem_used))
        local usage_percent=\$((mem_used_actual * 100 / mem_total))
        
        echo "Memory Usage: \${usage_percent}%"
        
        if [ "\$usage_percent" -ge "\$MEMORY_CRITICAL_THRESHOLD" ]; then
            echo "🚨 CRITICAL: Memory usage \${usage_percent}% >= \${MEMORY_CRITICAL_THRESHOLD}%"
            return 2
        elif [ "\$usage_percent" -ge "\$MEMORY_WARNING_THRESHOLD" ]; then
            echo "⚠️ WARNING: Memory usage \${usage_percent}% >= \${MEMORY_WARNING_THRESHOLD}%"  
            return 1
        else
            echo "✅ Memory usage normal: \${usage_percent}%"
            return 0
        fi
    fi
}

# Check disk usage
check_disk_usage() {
    local disk_usage=\$(df / | tail -1 | awk '{print \$5}' | sed 's/%//')
    
    echo "Disk Usage: \${disk_usage}%"
    
    if [ "\$disk_usage" -ge 90 ]; then
        echo "🚨 CRITICAL: Disk usage \${disk_usage}% >= 90%"
        return 2
    elif [ "\$disk_usage" -ge 75 ]; then
        echo "⚠️ WARNING: Disk usage \${disk_usage}% >= 75%"
        return 1
    else
        echo "✅ Disk usage normal: \${disk_usage}%"
        return 0
    fi
}

# Check load average
check_load_average() {
    local load_avg=\$(uptime | awk -F'load average:' '{print \$2}' | awk '{print \$1}' | sed 's/,//')
    local cpu_cores=\$(nproc)
    local load_ratio=\$(echo "\$load_avg * 100 / \$cpu_cores" | bc -l 2>/dev/null || echo "0")
    local load_percent=\${load_ratio%.*}  # Remove decimal part
    
    echo "Load Average: \${load_avg} (CPU cores: \${cpu_cores})"
    
    if [ "\$load_percent" -ge 200 ]; then
        echo "🚨 CRITICAL: Load ratio \${load_percent}% >= 200%"
        return 2
    elif [ "\$load_percent" -ge 150 ]; then
        echo "⚠️ WARNING: Load ratio \${load_percent}% >= 150%"
        return 1
    else
        echo "✅ Load average normal: \${load_percent}%"
        return 0
    fi
}

# Main monitoring function
main() {
    echo "🔍 Container Health Check: CT \$CONTAINER_ID (\$CONTAINER_NAME)"
    echo "📊 Type: \$CONTAINER_TYPE | Priority: \$PRIORITY"
    echo "⏰ Timestamp: \$(date)"
    echo ""
    
    local exit_code=0
    
    # Memory check
    check_memory_usage
    local mem_status=\$?
    [ \$mem_status -gt \$exit_code ] && exit_code=\$mem_status
    
    echo ""
    
    # Disk check  
    check_disk_usage
    local disk_status=\$?
    [ \$disk_status -gt \$exit_code ] && exit_code=\$disk_status
    
    echo ""
    
    # Load check
    check_load_average
    local load_status=\$?
    [ \$load_status -gt \$exit_code ] && exit_code=\$load_status
    
    echo ""
    echo "📋 Overall Status:"
    case \$exit_code in
        0) echo "✅ All systems normal" ;;
        1) echo "⚠️ Warning conditions detected" ;;
        2) echo "🚨 Critical conditions detected" ;;
    esac
    
    # Log to syslog for centralized monitoring
    logger -t "ct\${CONTAINER_ID}-monitor" "Health check completed with status \$exit_code"
    
    return \$exit_code
}

# Run main function
main
EOF
    
    # Make script executable
    chmod +x "$monitoring_script"
    
    # Copy script to container using Proxmox API
    echo "   📤 Copying monitoring script to container via API..."
    
    # Create monitoring directory and deploy script via API
    local setup_result=$(python3 -c "
import asyncio
import httpx
import base64

async def deploy_monitoring():
    client = httpx.AsyncClient(
        base_url='$PROXMOX_URL/api2/json',
        headers={'Authorization': '$PROXMOX_TOKEN'},
        verify=False,
        timeout=60.0
    )
    
    try:
        # Read the monitoring script
        with open('$monitoring_script', 'r') as f:
            script_content = f.read()
        
        # Create directory and deploy script using exec API
        create_dir_cmd = 'mkdir -p /opt/monitoring'
        response = await client.post('/nodes/$PROXMOX_NODE/lxc/$container_id/exec', data={
            'command': create_dir_cmd
        })
        
        if response.status_code != 200:
            print('❌ Failed to create monitoring directory')
            return False
        
        # Write script file
        write_script_cmd = f\"cat > /opt/monitoring/health_check.sh << 'EOF'\\n{script_content}\\nEOF\"
        response = await client.post('/nodes/$PROXMOX_NODE/lxc/$container_id/exec', data={
            'command': write_script_cmd
        })
        
        if response.status_code != 200:
            print('❌ Failed to write monitoring script')
            return False
        
        # Make script executable
        chmod_cmd = 'chmod +x /opt/monitoring/health_check.sh'
        response = await client.post('/nodes/$PROXMOX_NODE/lxc/$container_id/exec', data={
            'command': chmod_cmd
        })
        
        if response.status_code != 200:
            print('⚠️ Script deployed but chmod may have failed')
            return True  # Still consider success
        
        print('✅ Monitoring script deployed successfully')
        
        # Add to crontab
        cron_cmd = \"(crontab -l 2>/dev/null || true; echo '*/5 * * * * /opt/monitoring/health_check.sh >> /var/log/health_check.log 2>&1') | crontab -\"
        response = await client.post('/nodes/$PROXMOX_NODE/lxc/$container_id/exec', data={
            'command': cron_cmd
        })
        
        if response.status_code == 200:
            print('✅ Automated monitoring configured (every 5 minutes)')
        else:
            print('⚠️ Cron configuration may have failed')
        
        return True
        
    except Exception as e:
        print(f'❌ Error deploying monitoring: {e}')
        return False
    finally:
        await client.aclose()

success = asyncio.run(deploy_monitoring())
exit(0 if success else 1)
" 2>/dev/null)
    
    local deploy_result=$?
    echo "$setup_result"
    
    if [ $deploy_result -eq 0 ]; then
        echo "   ✅ API deployment completed successfully"
        
        # Quick test of the monitoring script via API
        echo "   🧪 Testing monitoring script via API..."
        python3 -c "
import asyncio
import httpx

async def test_monitoring():
    client = httpx.AsyncClient(
        base_url='$PROXMOX_URL/api2/json',
        headers={'Authorization': '$PROXMOX_TOKEN'},
        verify=False,
        timeout=30.0
    )
    
    try:
        test_cmd = '/opt/monitoring/health_check.sh'
        response = await client.post('/nodes/$PROXMOX_NODE/lxc/$container_id/exec', data={
            'command': test_cmd
        })
        
        if response.status_code == 200:
            print('✅ Monitoring script test completed')
        else:
            print('⚠️ Script test may have issues')
    except:
        print('⚠️ Could not test monitoring script')
    finally:
        await client.aclose()

asyncio.run(test_monitoring())
" 2>/dev/null
        
        return 0
    else
        echo "   ❌ Failed to deploy via API"
        return 1
    fi
    
    # Cleanup temporary file
    rm -f "$monitoring_script"
}

### MAIN EXECUTION ###

echo "🚀 Deploying Container Monitoring Scripts"
echo "=========================================="
echo "📊 Target: ${#CRITICAL_CONTAINERS[@]} critical containers"
echo "⏰ Timestamp: $(date)"
echo ""

successful_deployments=0
total_deployments=${#CRITICAL_CONTAINERS[@]}

for container_id in "${!CRITICAL_CONTAINERS[@]}"; do
    container_info="${CRITICAL_CONTAINERS[$container_id]}"
    
    # Check if container exists and is running via API
    status=$(python3 -c "
import asyncio
import httpx
import sys

async def check_container():
    client = httpx.AsyncClient(
        base_url='$PROXMOX_URL/api2/json',
        headers={'Authorization': '$PROXMOX_TOKEN'},
        verify=False,
        timeout=30.0
    )
    
    try:
        response = await client.get('/nodes/$PROXMOX_NODE/lxc/$container_id/status/current')
        if response.status_code == 200:
            print(response.json()['data']['status'])
        else:
            print('not_found')
    except:
        print('error')
    finally:
        await client.aclose()

asyncio.run(check_container())
" 2>/dev/null)
    
    if [ "$status" = "running" ]; then
        if deploy_monitoring_to_container "$container_id" "$container_info"; then
            ((successful_deployments++))
        fi
    elif [ "$status" = "stopped" ]; then
        echo "📦 CT $container_id: Skipped (status: stopped)"
    elif [ "$status" = "not_found" ]; then
        echo "📦 CT $container_id: Not found"
    else
        echo "📦 CT $container_id: Error checking status ($status)"
    fi
    echo ""
done

echo "📊 Deployment Summary:"
echo "  ✅ Successful: $successful_deployments/$total_deployments"
echo "  📈 Success Rate: $((successful_deployments * 100 / total_deployments))%"

if [ "$successful_deployments" -eq "$total_deployments" ]; then
    echo ""
    echo "🎉 All monitoring scripts deployed successfully!"
    echo "📊 Containers now monitored every 5 minutes"
    echo "📝 Logs available at: /var/log/health_check.log (in each container)"
    echo "🔍 Check status: pct exec [CONTAINER_ID] -- tail -f /var/log/health_check.log"
else
    echo ""
    echo "⚠️ Some deployments failed. Check container status and permissions."
fi

echo ""
echo "🔗 Integration with GitOps Framework:"
echo "  - Monitoring data feeds into ProxmoxContainerReport.json"
echo "  - Alerts logged to homelab-gitops-auditor dashboard"
echo "  - MCP servers available for automated responses"