version: '3.8'

services:
  homelab-gitops-auditor:
    image: homelab-gitops-auditor:latest
    container_name: homelab-gitops-auditor
    restart: unless-stopped
    ports:
      - "${API_PORT:-3071}:${API_PORT:-3071}"
      - "${METRICS_PORT:-9090}:${METRICS_PORT:-9090}"
    environment:
      # GitHub Configuration
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      
      # Home Assistant Configuration
      - HOME_ASSISTANT_SERVER=${HOME_ASSISTANT_SERVER}
      - HOME_ASSISTANT_HEALTH_ENDPOINT=${HOME_ASSISTANT_HEALTH_ENDPOINT}
      - DEPLOYMENT_PATH=${DEPLOYMENT_PATH:-/config}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-7}
      - DEPLOYMENT_TIMEOUT=${DEPLOYMENT_TIMEOUT:-300}
      
      # API Configuration
      - API_PORT=${API_PORT:-3071}
      - API_HOST=${API_HOST:-0.0.0.0}
      - CORS_ORIGIN_1=${CORS_ORIGIN_1}
      - CORS_ORIGIN_2=${CORS_ORIGIN_2:-http://localhost:3000}
      
      # Rate Limiting
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-60000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      
      # GitHub IP Ranges
      - GITHUB_IP_RANGE_1=${GITHUB_IP_RANGE_1:-140.82.112.0/20}
      - GITHUB_IP_RANGE_2=${GITHUB_IP_RANGE_2:-185.199.108.0/22}
      
      # MCP Configuration
      - NETWORK_FS_WRAPPER=${NETWORK_FS_WRAPPER:-/home/dev/workspace/network-mcp-wrapper.sh}
      - GITHUB_WRAPPER=${GITHUB_WRAPPER:-/home/dev/workspace/github-wrapper.sh}
      - MCP_TIMEOUT=${MCP_TIMEOUT:-30000}
      - MCP_RETRIES=${MCP_RETRIES:-3}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - LOG_OUTPUT=${LOG_OUTPUT:-/var/log/homelab-gitops-auditor/deployment.log}
      - LOG_MAX_SIZE=${LOG_MAX_SIZE:-10mb}
      - LOG_MAX_FILES=${LOG_MAX_FILES:-5}
      
      # Monitoring Configuration
      - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL:-60}
      - METRICS_PORT=${METRICS_PORT:-9090}
      
      # Alerting Configuration
      - ALERTING_ENABLED=${ALERTING_ENABLED:-true}
      - ALERT_WEBHOOK_URL=${ALERT_WEBHOOK_URL}
      - ALERT_CHANNEL_1=${ALERT_CHANNEL_1:-#ops}
      - ALERT_CHANNEL_2=${ALERT_CHANNEL_2:-#deployments}
      
      # Node Environment
      - NODE_ENV=${NODE_ENV:-production}
      
    volumes:
      - ./config:/app/config:ro
      - ./logs:/var/log/homelab-gitops-auditor
      - /home/dev/workspace:/workspace:ro
    networks:
      - homelab-gitops
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-3071}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.homelab.gitops.service=auditor"
      - "com.homelab.gitops.version=${VERSION:-latest}"

networks:
  homelab-gitops:
    driver: bridge
    name: homelab-gitops-network

volumes:
  logs:
    driver: local