name: Daily GitOps Audit

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Git Audit Script
        shell: pwsh
        run: |
          ./scripts/GitAudit.ps1

      - name: Commit updated report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/GitRepoReport.md
          git commit -m "📋 Daily audit report update" || echo "No changes to commit"
          git push
