name: Daily GitOps Audit

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show PowerShell version
        shell: pwsh
        run: |
          Write-Host "PowerShell version:"
          $PSVersionTable.PSVersion

      - name: Run Git Audit Script
        shell: pwsh
        run: |
          Write-Host "Running GitAudit.ps1..."
          try {
            ./scripts/GitAudit.ps1 -ErrorAction Stop
            Write-Host "✅ Audit script completed."
          } catch {
            Write-Host "❌ Script error: $($_.Exception.Message)"
            exit 1
          }

      - name: Commit and push updated report
        run: |
          git config user.name "GitOps Bot"
          git config user.email "bot@users.noreply.github.com"
          git add output/GitRepoReport.md

          git diff --cached --quiet || git commit -m "📋 Daily audit report update"

          git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/festion/homelab-gitops-auditor.git main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/festion/homelab-gitops-auditor.git HEAD:main
