name: Daily GitOps Audit

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:      # Allow manual trigger from GitHub UI

jobs:
  audit:
    name: Run GitOps Audit
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PowerShell (Debug)
        shell: pwsh
        run: |
          Write-Host "PowerShell version:"
          $PSVersionTable.PSVersion

      - name: Run Git Audit Script
        shell: pwsh
        run: |
          Write-Host "Running GitAudit.ps1..."
          try {
            ./scripts/GitAudit.ps1
            Write-Host "✅ Audit script completed."
          } catch {
            Write-Host "❌ Script error: $_"
            exit 1
          }

      - name: Commit updated report
        run: |
          git config user.name "GitOps Bot"
          git config user.email "bot@users.noreply.github.com"
          git add output/GitRepoReport.md

          # Only commit if there are changes
          git diff --cached --quiet || git commit -m "📋 Daily audit report update"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
