name: Daily GitOps Audit

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show PowerShell version
        shell: pwsh
        run: |
          Write-Host "PowerShell version:"
          $PSVersionTable.PSVersion

      - name: Run Git Audit Script
        shell: pwsh
        run: |
          Write-Host "Running GitAudit.ps1..."
          try {
            ./scripts/GitAudit.ps1 -ErrorAction Stop
            Write-Host "✅ Audit script completed."
          } catch {
            Write-Host "❌ Script error: $($_.Exception.Message)"
            exit 1
          }

      - name: Upload audit report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-audit-report
          path: output/GitRepoReport.md
          retention-days: 30

      - name: Display audit summary
        shell: pwsh
        run: |
          if (Test-Path "output/GitRepoReport.md") {
            Write-Host "✅ Audit report generated successfully"
            Write-Host "Report location: output/GitRepoReport.md"
          } else {
            Write-Host "❌ Audit report not found"
          }
