name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    name: Automated Code Quality

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files --show-diff-on-failure > quality-results.txt 2>&1 || true

      - name: Create quality report
        run: |
          echo "# 🔍 GitOps Auditor Code Quality Report" > quality-report.md
          echo "**Generated:** $(date)" >> quality-report.md
          echo "**Commit:** ${{ github.sha }}" >> quality-report.md
          echo "**Authentication:** Personal Access Token" >> quality-report.md
          echo "" >> quality-report.md
          echo "## Quality Check Results" >> quality-report.md
          echo "\`\`\`" >> quality-report.md
          cat quality-results.txt >> quality-report.md
          echo "\`\`\`" >> quality-report.md

          mkdir -p output
          cp quality-report.md output/CodeQualityReport.md

      - name: Upload quality report as artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-report
          path: output/CodeQualityReport.md
          retention-days: 30

      - name: Display quality results
        run: |
          echo "Quality check completed. Results:"
          cat quality-results.txt
