name: Lint and Test

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies (API)
      run: |
        cd api
        npm ci
    
    - name: Install dependencies (Dashboard)
      run: |
        cd dashboard
        npm ci
    
    - name: Lint API code
      run: |
        cd api
        npm run lint
    
    - name: Lint Dashboard code
      run: |
        cd dashboard
        npm run lint
    
    - name: TypeScript compilation check
      run: |
        cd dashboard
        npx tsc --noEmit
    
    - name: Test API endpoints
      run: |
        cd api
        npm test
    
    - name: Build Dashboard
      run: |
        cd dashboard
        npm run build
        
    - name: Run audit script validation
      run: |
        bash scripts/sync_github_repos.sh --dry-run
        
    - name: Code quality gate
      run: |
        echo "All linting and tests passed successfully"
