name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies (API)
      run: |
        cd api
        npm ci
    
    - name: Install dependencies (Dashboard)
      run: |
        cd dashboard
        npm ci
    
    - name: Run npm audit (API)
      run: |
        cd api
        npm audit --audit-level moderate
      continue-on-error: true
    
    - name: Run npm audit (Dashboard)
      run: |
        cd dashboard
        npm audit --audit-level moderate
      continue-on-error: true
    
    - name: Security scan with Snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
      continue-on-error: true
    
    - name: Run CodeQL Analysis
      if: github.event_name != 'schedule'
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
    
    - name: Perform CodeQL Analysis
      if: github.event_name != 'schedule'
      uses: github/codeql-action/analyze@v3
    
    - name: Scan shell scripts with ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        find scripts -name "*.sh" -exec shellcheck {} \;
      continue-on-error: true
    
    - name: Check for secrets in code
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified
      continue-on-error: true
