name: Weekly GitOps Audit Email

on:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 6AM UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository to known path
        uses: actions/checkout@v4
        with:
          path: homelab-gitops-auditor

      - name: Debug - Show working directory and all files
        shell: pwsh
        working-directory: homelab-gitops-auditor
        run: |
          Write-Host "Current directory: $(Get-Location)"
          Get-ChildItem -Recurse | ForEach-Object { Write-Host $_.FullName }

      - name: Run GitOps Audit Script
        shell: pwsh
        working-directory: homelab-gitops-auditor
        run: |
          $script = Join-Path $PWD "scripts/gitaudit.ps1"
          Write-Host "`nAttempting to run: $script"
          if (-Not (Test-Path $script)) {
            Write-Error "Script not found at $script"
            exit 1
          }
          & $script

      - name: Output HTML file contents
        shell: pwsh
        run: |
          $report = Get-Content homelab-gitops-auditor/output/GitRepoReport.html -Raw
          Write-Host "`n===== GitRepoReport.html =====`n"
          Write-Host $report

      - name: Send audit summary email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Weekly GitOps Audit Report"
          to: jeremy.ames@outlook.com
          from: GitOps Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello Jeremy,

            Your weekly GitOps audit has completed successfully.
            Please find the attached summary report.

            Regards,  
            GitOps Bot

          attachments: homelab-gitops-auditor/output/GitRepoReport.md
