name: 📬 Weekly GitOps Audit Email 

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  audit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: git config --global safe.directory '*'

      - name: Run GitOps Audit Script
        shell: pwsh
        run: ./scripts/GitAudit.ps1

<<<<<<< HEAD
      - name: Output Markdown summary to log
        shell: pwsh
        run: Get-Content output/GitRepoReport.md

      - name: Output HTML file contents
        shell: pwsh
        run: Get-Content output/GitRepoReport.html
=======
      - name: Show audit summary in logs
        shell: pwsh
        run: Get-Content output/GitRepoReport.md
>>>>>>> ef197e3405b1724aa53f1c30ac96bda014cac3e3

      - name: Send audit summary email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Weekly GitOps Audit Report"
          to: jeremy.ames@outlook.com
          from: GitOps Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello Jeremy,

<<<<<<< HEAD
            Your weekly GitOps audit completed successfully.

            ✔️ Repository count: 5
            📁 Report includes:
              - Last commit per repo
              - Current branch
              - Uncommitted changes (if any)

            📎 Full details are attached in the HTML report.

            Cheers,  
            GitOps Bot
          attachments: output/GitRepoReport.html

=======
            Your weekly GitOps audit has completed successfully.

            Here's a quick summary:
            ${{ steps.summary.outputs.short }}

            📎 Full details are attached in the HTML report.

            Cheers,
            GitOps Bot
          attachments: output/GitRepoReport.html
>>>>>>> ef197e3405b1724aa53f1c30ac96bda014cac3e3
