name: 📬 Weekly GitOps Audit Email

on:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 6AM UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git (for repo commands)
        run: git config --global safe.directory '*'

      - name: Run GitOps Audit Script
        shell: pwsh
        run: |
          ./scripts/GitAudit.ps1
      - name: Debug audit output
        shell: pwsh
        run: |
         Get-Content output/GitRepoReport.md
    
      - name: Send audit summary email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Weekly GitOps Audit Report"
          to: jeremy.ames@outlook.com
          from: GitOps Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello Jeremy,

            Your weekly GitOps audit has completed successfully.

            Summary:
            - ✅ Repository audits completed
            - 🚫 Any skipped releases are noted
            - 📦 Attached: GitRepoReport.md

            Have a great week! 🚀
          attachments: output/GitRepoReport.md
