name: Weekly GitOps Audit Email

on:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 6AM UTC
  workflow_dispatch:
    inputs:
      mode:
        description: 'Run mode (default or test)'
        required: false
        default: 'default'

jobs:
  audit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: homelab-gitops-auditor

      - name: Root-level debug - Show full file tree
        shell: pwsh
        run: |
          Write-Host "🔍 Full file tree from runner root:"
          Get-ChildItem -Recurse | ForEach-Object { Write-Host $_.FullName }

      - name: Run GitOps Audit Script
        shell: pwsh
        working-directory: homelab-gitops-auditor
        run: |
          $script = "scripts/gitaudit.ps1"
          $mode = "${{ github.event.inputs.mode }}"
          Write-Host "`nRun mode: $mode"
          Write-Host "`nAttempting to run: $script"
          if (-Not (Test-Path $script)) {
            Write-Error "Script not found at $script"
            exit 1
          }
          if ($mode -eq "test") {
            Write-Host "🧪 Injecting test repo: repos/testrepo/.git"
            New-Item -ItemType Directory -Path "repos/testrepo/.git" -Force | Out-Null
          }
          & $script

      - name: Confirm report files exist
        shell: pwsh
        working-directory: homelab-gitops-auditor
        run: |
          Write-Host "`n📂 Output directory contents:"
          Get-ChildItem output | ForEach-Object { Write-Host $_.FullName }

      - name: Output HTML file contents
        shell: pwsh
        working-directory: homelab-gitops-auditor
        run: |
          Get-Content output/GitRepoReport.html -Raw

      - name: Send audit summary email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Weekly GitOps Audit Report"
          to: jeremy.ames@outlook.com
          from: GitOps Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello Jeremy,

            Your weekly GitOps audit has completed successfully.
            Please find the attached HTML summary report.

            Regards,  
            GitOps Bot

          attachments: output/GitRepoReport.html
