name: Weekly GitOps Audit Email

on:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 6AM UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository to root
        uses: actions/checkout@v4
        with:
          path: .

      - name: Run GitOps Audit Script
        shell: pwsh
        run: |
          $script = "scripts/gitaudit.ps1"
          Write-Host "`nAttempting to run: $script"
          if (-Not (Test-Path $script)) {
            Write-Error "Script not found at $script"
            exit 1
          }
          & $script

      - name: Confirm report files exist
        shell: pwsh
        run: |
          Write-Host "`n📂 Output directory contents:"
          Get-ChildItem output | ForEach-Object { Write-Host $_.FullName }

      - name: Output HTML file contents
        shell: pwsh
        run: |
          Get-Content output/GitRepoReport.html -Raw

      - name: Send audit summary email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Weekly GitOps Audit Report"
          to: jeremy.ames@outlook.com
          from: GitOps Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello Jeremy,

            Your weekly GitOps audit has completed successfully.
            Please find the attached HTML summary report.

            Regards,  
            GitOps Bot

          attachments: output/GitRepoReport.html
